Data Structures/Controllers/StackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Data_Structures.Controllers
{
    public class StackController : Controller
    {
        static Stack<string> myStack = new Stack<string>();
        // GET: Stack
        public ActionResult Index()
        {
            ViewBag.MyStack = myStack;
            return View();

        }
        public ActionResult AddOne()
        {
            myStack.Push("New Entry " + (myStack.Count + 1));

            ViewBag.MyStack = myStack;

            return View("Index");
        }
        public ActionResult AddList()
        {
            myStack.Clear();
            for (int StackCounter = 0; StackCounter < 2000; StackCounter++)
            {
                
                myStack.Push("New Entry " + (myStack.Count + 1));

                ViewBag.MyStack = myStack;
            }

            return View("Index");
            
        }
        public ActionResult Display()
        {
            foreach (var x in myStack)
            {
                ViewBag.MyStack = myStack;
            }
                return View("StackDisplay");
        }
        public ActionResult Delete()
        {
            if (myStack.Count > 0)
            {
                myStack.Pop();
                return View("Index");
            }
            else
            {
                return View("StackDisplay");
            }
            
        }
        public ActionResult Clear()
        {
            while (myStack.Count > 0)
            {
                myStack.Clear();
            }
            return View("StackDisplay");
        }
        public ActionResult Search()
        {
            if (myStack.Count > 0)
            {
                string SearchTerm = "New Entry 1450";
                System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
                sw.Start();
                string Found = "found";
                string NotFound = "not found";
                ViewBag.Status = NotFound;
                for (int counter = 0; counter < myStack.Count(); counter++)
                {
                    if (SearchTerm == myStack.ElementAt(counter))
                    {
                        sw.Stop();
                        TimeSpan fs = sw.Elapsed;
                        ViewBag.StopWatch = fs;
                        ViewBag.Status = Found;
                        return View("Index");
                    }

                }
                sw.Stop();
                TimeSpan ts = sw.Elapsed;
                ViewBag.StopWatch = ts;
                return View("Index");
            }
            else
            {
                return View("StackDisplay");
            }
        }
        public ActionResult Menu()
        {
            return View("~/Views/Home/Index.cshtml");
        }
    }
}

Data Structures/Views/Stack/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Stack Index</h2>

<body>
    <div>
        <ul>
            <li>
                <a href="@Url.Action("AddOne", "Stack")" class="w3-bar-item w3-button">Add One Item to Stack</a>
            </li>
        </ul>
    </div>

    @foreach (var sData in ViewBag.MyStack)
    {
        <p>@sData</p>
    }
</body>

Data Structures/Views/Stack/StackDisplay.cshtml
@{
    ViewBag.Title = "StackDisplay";
}

<h2>Stack Index</h2>

<body>
    <div>
        <ul>
            <li>
                <a href="@Url.Action("AddOne", "Stack")" class="w3-bar-item w3-button">Add One Item to Stack</a>
            </li>
            <li>
                <a href="@Url.Action("AddList", "Stack")" class="w3-bar-item w3-button">Add Huge List of Items to Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Display", "Stack")" class="w3-bar-item w3-button">Display Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Delete", "Stack")" class="w3-bar-item w3-button">Delete Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Clear", "Stack")" class="w3-bar-item w3-button">Clear Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Search", "Stack")" class="w3-bar-item w3-button">Search Stack</a>
            </li>
            <li>
                <a href="@Url.Action("Menu", "Stack")" class="w3-bar-item w3-button">Return</a>
            </li>
        </ul>
    </div>
@if (ViewBag.MyStack != null)
{
       foreach (var sData in ViewBag.MyStack)
       {
        <p>@sData</p>
       }
}
else
{
    <p>There is nothing in the stack.</p>
}

</body>

Data Structures/Views/Stack/Stopwatch.cshtml
@{
    ViewBag.Title = "StopWatch";
}

<h2>Stopwatch</h2>

<p>The entry was @ViewBag.Status</p> 
<p>Total time for search: @ViewBag.Stopwatch</p>