Data Structures/Controllers/DictionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace Data_Structures.Controllers
{
    public class DictionaryController : Controller
    {
        static Dictionary<int, string> myDictionary = new Dictionary<int, string>();
        // GET: Dictionary
        public ActionResult Index()
        {
            ViewBag.MyDictionary = myDictionary;
            return View();
        }
        public ActionResult AddOne()
        {
            myDictionary.Add(myDictionary.Count, "New entry " + (myDictionary.Count + 1));
            ViewBag.MyDictionary = myDictionary;
            return View("Index");
        }
        public ActionResult AddHuge()
        {
            for (int i = 0; i <= 2000; i++)
            {
                myDictionary.Add(myDictionary.Count, "New entry " + (myDictionary.Count + 1));
                ViewBag.MyDictionary = myDictionary;
            }
            return View("Index");
        }
        public ActionResult Display()
        {
            foreach (KeyValuePair<int, string> item in myDictionary)
            {
                ViewBag.MyDictionary = myDictionary;
            }
            return View("Display");
        }
        public ActionResult Delete()
        {
            int x = 10;
            if (myDictionary.Count > 0)
            {
                myDictionary.Remove(x);
            }
            if (myDictionary.Count < 10)
            {
                ViewBag.ErrorMessage = "There is no item to delete.";
            }
            return View("Index");
        }
        public ActionResult Clear()
        {
            while (myDictionary.Count > 0)
            {
                myDictionary.Clear();
            }
            ViewBag.MyDictionary = myDictionary;
            return View("Index");
        }
        public ActionResult Search()
        {
            System.Diagnostics.Stopwatch sw = new System.Diagnostics.Stopwatch();
            int searchValue = 40;
            sw.Start();
            //loop to do all the work

            foreach (KeyValuePair<int, string> entry in myDictionary)
            {
                if (entry.Key == searchValue)
                {
                    sw.Stop();
                    TimeSpan fs = sw.Elapsed;
                    ViewBag.Stopwatch = fs;
                    ViewBag.Status = "Found";
                    return View("Index");
                }
            }
            sw.Stop();
            TimeSpan ts = sw.Elapsed;
            ViewBag.Stopwatch = ts;
            ViewBag.Status = "Not Found";
            return View("Index");
        }
        public ActionResult Return()
        {
            return View("~/Views/Home/Index.cshtml");
        }
    }
}

Data Structures/Views/Dictionary/Display.cshtml
@{
    ViewBag.Title = "Index";
}
<h2>Dictionary Index</h2>
<body>
    <div>
        <ul>
            <li>
                <a href="@Url.Action("AddOne", "Dictionary")" class="w3-bar-item w3-button">Add One Item to Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("AddHuge", "Dictionary")" class="w3-bar-item w3-button">Add Huge List of Items to Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Display", "Dictionary")" class="w3-bar-item w3-button">Display Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Delete", "Dictionary")" class="w3-bar-item w3-button">Delete from Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Clear", "Dictionary")" class="w3-bar-item w3-button">Clear Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Search", "Dictionary")" class="w3-bar-item w3-button">Search Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Return", "Dictionary")" class="w3-bar-item w3-button">Return to Main Menu</a>
            </li>
        </ul>
    </div>
    @if (ViewBag.MyDictionary != null)
    {
        foreach (KeyValuePair<int, string> entry in ViewBag.MyDictionary)
        {
            <p>@entry.Value</p>
        }
    }
    else
    {
        <p>There is nothing in the dictionary.</p>
    }
</body>

Data Structures/Views/Dictionary/Index.cshtml


@{
    ViewBag.Title = "Index";
}
<h2>Dictionary Index</h2>
<body>
    <div>
        <ul>
            <li>
                <a href="@Url.Action("AddOne", "Dictionary")" class="w3-bar-item w3-button">Add One Item to Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("AddHuge", "Dictionary")" class="w3-bar-item w3-button">Add Huge List of Items to Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Display", "Dictionary")" class="w3-bar-item w3-button">Display Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Delete", "Dictionary")" class="w3-bar-item w3-button">Delete from Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Clear", "Dictionary")" class="w3-bar-item w3-button">Clear Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Search", "Dictionary")" class="w3-bar-item w3-button">Search Dictionary</a>
            </li>
            <li>
                <a href="@Url.Action("Return", "Dictionary")" class="w3-bar-item w3-button">Return to Main Menu</a>
            </li>
        </ul>
    </div>
    @ViewBag.ErrorMessage
    @if (ViewBag.StopWatch != null)
    {
        <p>The entry was @ViewBag.Status.</p>
        <p>Total time for search: @ViewBag.Stopwatch seconds.</p>
    }
</body>


